name: armoyu_widgets
description: "ARMOYU Widget kütüphanesidir"
repository: https://github.com/aramizdakioyuncu/armoyu_widgets
version: 1.0.0+3

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  device_info_plus: ^10.0.1
  package_info_plus: ^8.0.1
  crypto: ^3.0.3
  image_picker: ^1.0.7
  image_cropper: ^8.0.1
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.3
# //
  flutter_mentions: ^2.0.1
  flutter_multi_formatter: ^2.12.8
  cached_network_image: ^3.3.0
  get: ^4.6.6
  url_launcher: ^6.3.1

  armoyu_services: ^1.0.0+23

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true