name: armoyu_widgets
description: "ARMOYU Widget kütüphanesidir"
repository: https://github.com/aramizdakioyuncu/armoyu_widgets
version: 1.0.0+34

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  device_info_plus: ^10.0.1
  package_info_plus: ^8.0.1
  crypto: ^3.0.3
  image_picker: ^1.0.7
  image_cropper: ^8.0.1
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.3
  # //
  flutter_mentions: ^2.0.1
  flutter_multi_formatter: ^2.12.8
  cached_network_image: ^3.3.0
  get: ^4.6.6
  get_storage: ^2.1.1

  url_launcher: ^6.3.1

  armoyu_services: ^1.0.0+40

  like_button: ^2.0.5
  share_plus: ^10.1.2
  photo_manager: ^3.6.1
  photo_view: ^0.15.0
  camera: ^0.11.0+1
  connectivity_plus: ^6.0.1
  fluttertoast: ^8.2.4
  shimmer: ^3.0.0
  video_player: ^2.8.3
  chewie: ^1.7.5
  pinch_zoom: ^2.0.0
  detectable_text_field: ^3.0.2
  marquee: ^2.3.0
  socket_io_client: ^3.0.0
  audioplayers: ^6.1.0
  carousel_slider: ^5.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
