name: widgets
description: 'A new Flutter project.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependency_overrides:
  armoyu_widgets:
    path: ../../

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  armoyu_widgets:
    path: ../../

  http: ^1.2.2
  device_info_plus: ^10.0.1
  package_info_plus: ^8.0.1
  crypto: ^3.0.3
  image_picker: ^1.0.7
  image_cropper: ^8.0.1
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.3
  get: ^4.6.6
  url_launcher: ^6.3.1

  photo_manager: ^3.6.1
  photo_view: ^0.15.0
  
  flutter_mentions: ^2.0.1
  flutter_multi_formatter: ^2.12.8
  cached_network_image: ^3.3.0
  font_awesome_flutter: ^10.8.0
  marquee: ^2.3.0
  socket_io_client: ^3.0.0
  audioplayers: ^6.1.0
  carousel_slider: ^5.0.0
  flutter_webrtc: ^0.12.12


  armoyu_services: ^1.0.0+53




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/